spring:
  application:
    name: "medinote-back-spring"

  config:
    import: optional:file:.env[.properties]
#  profiles:
#    active: oauth2, openai, aws

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

#  h2:
#    console:
#      path: /h2-console
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:test
  datasource:
    url: ${DB-URL}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}

  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100 #

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - email
              - profile

#          kakao:
#            client-id: ${KAKAO-CLIENT-ID}
#            client-secret: ${KAKAO-CLIENT-SECRET}
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
#              - profile_nickname
#              - profile_image
#              - account_email
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#            client-name: Kakao
          naver:
            client-id: ${NAVER-CLIENT-ID}
            client-secret: ${NAVER-CLIENT-SECRET}
            redirect-uri: "${SERVER-URL}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - nickname
              - email
              - profile_image

        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  cloud:
    aws:
      region:
        static: ${AWS-REGION}
      credentials:
        access-key: ${AWS-ACCESS-KEY}
        secret-key: ${AWS-SECRET-KEY}
      sqs:
        queue-name: ${SQS-QUEUE-NAME}
      s3:
        bucket-name: ${S3-BUCKET-NAME}

# jwt secret key 설정
jwt:
  secret: ${JWT-SECRET}

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    token-secret: ${AUTH-TOKEN-SECRET}
    token-expiry: 1800000
    refresh-token-expiry: 604800000
  oauth2:
    authorized-redirect-uris:
      - ${REACT-URL}/oauth2/redirect


logging:
  level:
    org.springframework: debug

openai:
  api-key: ${OPENAI-API-KEY}
  gpt-model: "gpt-3.5-turbo"
  audio-model: "whisper-1"
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    transcription-url: /audio/transcriptions