spring:
  application:
    name: "medinote-back-spring"

  profiles:
    active: oauth2, openai, aws

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100 #

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - email
              - profile

#          kakao:
#            client-id: ${KAKAO-CLIENT-ID}
#            client-secret: ${KAKAO-CLIENT-SECRET}
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
#              - profile_nickname
#              - profile_image
#              - account_email
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#            client-name: Kakao
          naver:
            client-id: ${NAVER-CLIENT-ID}
            client-secret: ${NAVER-CLIENT-SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - nickname
              - email
              - profile_image

        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# cors 설정
cors:
  allowed-origins:
    - 'http://localhost:5173'
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed-headers:
    - '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: ${JWT-SECRET}

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    token-secret: ${AUTH-TOKEN-SECRET}
    token-expiry: 1800000
    refresh-token-expiry: 604800000
  oauth2:
    authorized-redirect-uris:
      - http://localhost:5173/oauth2/redirect


#logging:
#  level:
#    org.springframework: info
openai:
  api-key: ${API-KEY}
  gpt-model: ${GPT-MODEL}
  audio-model: ${WHISPER-MODEL}
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    transcription-url: /audio/transcriptions

s3:
  bucket-name: ${S3.BUCKET-NAME}
